### ISSUE TITLE
Welcome!

### ISSUE THREAD

**Issue by JestonBlu** [JestonBlu/Neighbor-Works#1]
We can use the issues section to post discussion threads

**Comment by nitroys** [comment]
Thanks for setting this up, Joseph! Commenting so you have my username and can add me as a collaborator.

-Shannon

**Comment by rmglazner** [comment]
Thank you! I am also commenting so that you have my username.

**Comment by profgeraci** [comment]
This is great, Joseph.  My username is NancyDrew484 and it is associated with my personal e-mail profgeraci@gmail.com.  

- Anne

**Comment by JestonBlu** [comment]
Ive added everyone as collaborators so you should all have an invite in
your inbox that you will need to accept, then we should be good to go. I
can will set up a basic folder structure so we can start playing around.

**Comment by JestonBlu** [comment]
@nitroys @rmglazner @NancyDrew484 

I have added the data set in a few different forms and I also created a JMP project file to play around with. I also started reclassifying some of the variables, but then stopped because Im guessing we will not use them all... I do have a general question about the data. Is the satisfaction score a an ordinal variable?

**Comment by rmglazner** [comment]
Ordinal seems right, nominal may also work but it would not be as specific.
Thanks for putting that together!

Rachael
