### ISSUE TITLE
Presentation and Report

### ISSUE THREAD

**Issue by rmglazner** [JestonBlu/Neighbor-Works#10]
I have uploaded the first draft of the presentation to the Code.

Some of the questions and issues I had were:

1) Are there any images we could include with the background slides?
2) Should we show a JMP model with all of the variables before we show the reduced model? This also applies to the report.
3) The table on the Data Source slide is only temporary, until we decide how we want to create it for the report.
4) The discussion for the report should have greater detail, which is why I had some questions in the PowerPoint on the last slide.

I was not sure how to replace the most recently edited report with more comments, so I uploaded a separate document called Project1 Writeup NWRoc EDITS RG.

Please let me know any changes you think should be made!

**Comment by rmglazner** [comment]
@JestonBlu @NancyDrew484 @nitroys

**Comment by nitroys** [comment]
I think it looks really good! I've made some changes to the report based on your suggestions, they're in the file with my initials at the end. I added some more items to the discussion which may help answer the questions at the end of your slide.

**Comment by profgeraci** [comment]
OK, I've accepted some of the cosmetic changes to the document, but there are still some issues to resolve - see Rachael's comments in the latest document.    We're looking good so far. 

NOTE:  To update the document, just click "View Raw".  Turn on track changes or add comments, then SAVE the file with the same name.  To upload it back to GITHUB, just drag it on top of your browser.  You don't need to create a new named file each time.

**Comment by rmglazner** [comment]
Thank you both for your comments! Also, thank you for helping me understand how to replace a file!

**Comment by rmglazner** [comment]
Should we include an intercept in our models in the report and PowerPoint?

**Comment by JestonBlu** [comment]
I think the report looks really good. Nice work. Im having trouble adding a contrast to the ancova model in JMP. I wonder if that is mainly used in mixed models. I think I can get it added to the SAS script tomorrow. The main difference between the SAS script and the JMP scripts is that I chose mixed model in SAS which estimates the variance a little different, but I can add a contrast. I will try to do it in SAS tomorrow and see what it looks like. There is currently an intercept in the model though.

**Comment by rmglazner** [comment]
Okay, thank you! I am sorry for my confusing wording but I meant writing an intercept in the model statement, when we are writing all of our factors out. Before we show our results, should we state log(years)= intercept + factor + factor?

Thank you again for the additional coding!

**Comment by JestonBlu** [comment]
Yeah, so in the analysis folder I have a file named summary where I have written the formulas of the models and I included an intercept in the latex version. I think you are right that we should include an intercept term in the written model.. can the word doc support latex? Or maybe we can put it in an online latex generator to create a pic of the formula. I think we may be expected to show the model like I have below where we use the letters for covariance variables and greek letters for fixed effects. Also showing the subscripts and their levels and definitions.

**Current Best Model**

**Latex version**
$y_{ijklmn} = \beta_0 + \beta_1(a) + \alpha_i + \gamma_j + \delta_k + \tau_l + \theta_m + e_{ijklmn}$

```
beta_0    -> overall mean
beta_1    -> age coefficient
a         -> age value
alpha_i   -> 1,2,3   (police rating: low, medium, high)
gamma_j   -> 1,2,3   (trash rating: low, medium, high)
delta_k   -> 1,2     (safety day rating: medium, high)
tau_l     -> 1,2,3   (Own/Rent: other, own, rent)
theta     -> 1,2,3,4 (Neighborhood)

e_{ijklm} -> model error N(0, \sigma^2)
```

**Comment by rmglazner** [comment]
I know it is possible to add Greek letters and subscripts to word documents, and then that can be copied and pasted to the presentation. I agree it would be better to state the models as you have suggested. Thank you for sharing that!

**Comment by JestonBlu** [comment]
I should have just posted this... this is along the lines of what I was thinking. I can pretty it up if we want to go this route.

![codecogseqn](https://cloud.githubusercontent.com/assets/3339909/23387881/ca4675ec-fd24-11e6-9729-99a39dda0cad.gif)


```latex

\begin{align*}
y_{ijklmn} = & \text{ }\beta_0 + \beta_1(a) + \alpha_i + \gamma_j + \delta_k + \tau_l + \theta_m + e_{ijklmn} \\
\\
\beta_0: & \text{  overall mean}                    \\
\beta_1: & \text{  age coefficient}                 \\
a: &       \text{age}                               \\
\alpha_i: &  [1,2,3] \text{  (police rating: low, medium, high)} \\
\gamma_j: &  [1,2,3] \text{  (trash rating: low, medium, high)}  \\
\delta_k: &  [1,2]   \text{  (safety day rating: medium, high)}  \\
\tau_l:   &  [1,2,3] \text{  (Own/Rent: other, own, rent)} \\
\theta_m:  &  [1,2,3,4] \text{  (Neighborhood)} \\
e_{ijklmn}: & \text{  }N(0, \sigma^2) \\

\end{align*}
```

**Comment by JestonBlu** [comment]
I have cleaned up the reports folder and archived the other models we tried. Right now im just showing the best model in the main folder.  The JMP version used a GLM model with least squares.  The SAS version is a mixed model with REML. Both end up having the same significant variables, but I couldnt figure out how to add contrasts to the GLM model in JMP so I just added it to the SAS mixed model. 

I also realized that the SAS report was broken up so I produced it as an html file this time so its easier to read. Also here are the results of the contrasts.

![image](https://cloud.githubusercontent.com/assets/3339909/23410939/815782c8-fd96-11e6-8596-d3cabe61c5b8.png)

I also updated the SAS code with the current best model if anyone wants to play with it.

**Comment by rmglazner** [comment]
Thank you for adding this information, this helps a lot! For the model, should there also be a description indicating that y is years? I will add the new version of the model as well as the contrast to the presentation before our meeting tomorrow!

**Comment by rmglazner** [comment]
I cannot see the changes that were made to the report since I last commented on it. I don't know if it is because I cannot find the correct document or if it something else?

**Comment by JestonBlu** [comment]
which document?

**Comment by JestonBlu** [comment]
Are you looking at the website or at your local copy? You may need to pull the latest changes.

**Comment by rmglazner** [comment]
Shannon said she had added items to the discussion and made some changes based on some of my comments, but when I try to open the document looks the same. I am using the website, and I tried downloading the desktop version of GitHub but I had no idea how to get it to work. Can I pull the latest changes online, or do I need to do that from the desktop? Sorry about the confusion, I have never used GitHub before this project!

**Comment by nitroys** [comment]
Hmm yeah it looks like our two documents were consolidated, but my changes weren't made. I can reupload it, I think.

**Comment by nitroys** [comment]
Okay! It's there now.

**Comment by JestonBlu** [comment]
Yeah, the website has the "Master" version, it will always be the most up to date.

**Comment by rmglazner** [comment]
I was able to view the changes made to the most recent report document that Shannon uploaded! Thank you both for your help!

**Comment by rmglazner** [comment]
Thank you for making those changes! Overall it is looking good, but the title still needs to be changed so that it matches the title of the PowerPoint I uploaded. Can you please change the title to "Identifying Factors Associated with Residence in Subsectors of a Rochester Neighborhood"?

Other than that, the only other comment I have is if you can please add a sentence or to about why we chose to use log(years) rather than just years.

Some of my comments from previous drafts still appear on the final writeup, so as long as you delete those before submission it should be okay!

Thank you again!
