### ISSUE TITLE
Taxi Analysis

### ISSUE THREAD

**Issue by JestonBlu** [JestonBlu/Neighbor-Works#16]
@NancyDrew484 @nitroys @rmglazner 

I spent a good bit of time this weekend looking at the taxi cab data and I have come across an issue with the data. I dont think we are going to be able to use logistic regression to predict if the cab drivers was tipped. When I looked at the data I noticed that there is not tip data for almost anyone who paid cash for the fare. I confirmed this by looking at the documentation.

![image](https://cloud.githubusercontent.com/assets/3339909/25073205/3a844a58-22a7-11e7-9e64-1451055f44e5.png)

I fit some preliminary models, one using logistic regression with the response equal to a binary indicator if the cab driver was tipped with cash customers removed and I also tried doing binomial regression where the response is the proportion of tip to the total fare. Both models were worthless.  

I did Shannon's original idea and fit a linear regression model on the amount of tip and the fit was much better, but with an r^2 in the 50s so still not great. So far I have just used the following predictors: 

* month
* rate_code
* pickup_time
* passenger_count
* trip_distance
* fare_amount
* toll (binary indicator)

At this point would recommend regular linear regression, although we might try a few other methods that Dr. Akleman has gone over.

Probably the most interesting thing about this data is the location data.  Ive been messing around with some of the pick up and drop off locations to see if there are any significant differences that we could investigate.

I was thinking that if we could break the locations down into high level districts, then maybe we could use pick up or drop off locations as predictors and then potentially try logistic regression again.

Here are a few density plots I have made with the taxi data on top of  a map of New York

![image](https://cloud.githubusercontent.com/assets/3339909/25073346/100ffaa8-22aa-11e7-9e46-c9fb8beaea68.png)

![image](https://cloud.githubusercontent.com/assets/3339909/25073353/492a3510-22aa-11e7-9164-0a5ca687d43b.png)

**Comment by profgeraci** [comment]
Looks like a good start, Joseph.  Could you share the SAS code that you're using, so that we can all play around with the models? 

I've filled in a basic document structure in the Project Document that Shannon established and shared on Google Docs:
https://docs.google.com/document/d/10ZL-BVg78XcBX92qKh3xLWf0zxTctK7ROLLHT0NNOpM/edit?ts=58f005c6

I'll need more details about exactly what data we extracted (dates) and how it was sampled (I think you said a stratified sample).  

- Anne

**Comment by rmglazner** [comment]
Thank you, Anne and Joseph! Is the Google document you linked to the one that I originally shared, or did Shannon create a separate one? I just want to check so that I write everything in the correct place!

**Comment by rmglazner** [comment]
I added a short description of background and methods, but I am not sure what else to add. Thoughts?

**Comment by profgeraci** [comment]
If you use the link above, you'll see the correct document.  I can see the text that you added this morning, Rachael.  If you click on the words "last edit was xxx minutes ago" near the top of the screen, you can see each person's contributions or edits.  Looks like the document is working. 

Now we just need to figure out what to write.

**Comment by rmglazner** [comment]
Great, thank you! The good news is that for this project, we have an 8 page limit so there is more room to add models and to write compared to part 1 of the project.

**Comment by JestonBlu** [comment]
I just posted a short R script that I used to do some exploratory analysis in the new folder called Taxi.

**Comment by profgeraci** [comment]
Interesting article in the NYT this morning:

https://nyti.ms/2pwX3Jr

**Comment by rmglazner** [comment]
Thanks for sharing! An interesting story about tips - My first job was at Dunkin Donuts. There was a tip jar that customers could add money to if they wanted. I soon discovered that the policy of the Dunkin Donuts I worked at was that you had to report your tips so that it could be removed from your paycheck... If customers knew that, they probably wouldn't be tipping at all since that money did not go to the crew members.

If possible, we should try to have some results completed by Friday so that I have time to put together a presentation and record it before Monday. That way we can maybe meet Monday and you can provide feedback for the video. I will create a blank Google presentation document and share it with you all today.

**Comment by rmglazner** [comment]
I have just shared to presentation document with you all. Here is the link as well: https://docs.google.com/a/tamu.edu/presentation/d/1skXgxYvMRobi20H31xHaBal5kLPRN9Ni310mq-0ZZy8/edit?usp=sharing

**Comment by profgeraci** [comment]
![image](https://cloud.githubusercontent.com/assets/8108754/25141042/475ea720-2430-11e7-9a93-5a3da1f91533.png)

Hmmmmm, this data doesn't look right.  When I do descriptive statistics on the DTA (original) data I get:
![image](https://cloud.githubusercontent.com/assets/8108754/25140683/27dd0ed8-242f-11e7-9735-fcad989b6a48.png)
The average TOTAL_AMOUNT is 0.271 ($0.27?)? 

..... or the CTA (processed data):

![image](https://cloud.githubusercontent.com/assets/8108754/25141000/2465c88e-2430-11e7-9399-c2c8027361de.png)
![image](https://cloud.githubusercontent.com/assets/8108754/25140932/ebd30e3c-242f-11e7-85a6-3976ed578cbd.png)

... the average tip_pct is 39.965, but I don't see a column for the total amount of the trip. 

What am I missing here?

**Comment by nitroys** [comment]
I'm not sure? When I run proc univariate on the sample I posted in code, I get 15.19 as the mean total amount, 1.5 for mean tip amount, and .087 for the average tip percentage of total amount.

**Comment by JestonBlu** [comment]
I have done a lot of filtering of the original data to get rid of a lot of outliers and potentially bad records.. i narrowed down the data set to only transactions paid by credit card because those are the only records with tip data. 

I think we should really try to use the location data so I have been working to break up the lat and lon data points into groups.. so far I have used KMeans clustering to associate each location with a geographic center. This plot shows the centers the algorithm has chosen based on the density of the data.

![image](https://cloud.githubusercontent.com/assets/3339909/25157530/953401f2-2467-11e7-8b10-992598b4b78e.png)

Next Ive done some geocoding using the google API and so i can assign physical locations to each of the points and associate a pickup or dropoff location with a general area. I think that will allow us to use general locations so see if it plays a role in tip amount or maybe back to logistic regression where we can look at the probability of a passenger tipping.

I should be able to get a prepped data set into SAS tomorrow. So far Ive been mainly working in R because thats my wheelhouse.  I think some of these visuals might make our presentation look pretty good to.

Here is another map that shows the clusters of locations I am planning on using.. there are different clusters for pickup and drop off locations so this one is just showing a map of the pickup locations...  

What do you guys think?

![image](https://cloud.githubusercontent.com/assets/3339909/25157614/166c51b6-2468-11e7-8042-e540466a6b6a.png)

**Comment by rmglazner** [comment]
The map with the color-coded grouping is really impressive! I will add it to the project document. I think that narrowing down the data for the reasons you have written here are fine. Can you also upload an image of the drop-off locations? I agree that these maps will make our project look great!

**Comment by nitroys** [comment]
I think this is super cool. I've never done any geographic assignment stuff like this, so I'm really impressed. I think we could also consider using pickup locations to predict trip distance or total fare amount too. They might be cleaner response variables than tip, and we could use a random coefficient model, where pick up location is a random effect.

**Comment by JestonBlu** [comment]
Im good with that Shannon, might as well try anything that looks interesting.

Here is the same plot with the dropoff locations

![image](https://cloud.githubusercontent.com/assets/3339909/25159670/fefdb66e-2476-11e7-9ee5-b06220b57df9.png)

As an example here are the first couple of cluster locations that I pulled from google. If you want to check out the R code, I have updated my exploratory.R script.

```
> head(i.cen)

  dropoff_latitude dropoff_longitude                                 dropoff.centers dropoffID
1         40.69272         -73.92308         10 Bleecker St, Brooklyn, NY 11221, USA         1
2         40.71593         -73.95394        26 Havemeyer St, Brooklyn, NY 11211, USA         2
3         40.80406         -73.93871         119 E 124th St, New York, NY 10035, USA         3
4         40.77104         -73.98218          1887 Broadway, New York, NY 10023, USA         4
5         40.76621         -73.95610          411 E 70th St, New York, NY 10021, USA         5
6         40.76574         -73.91986 33-02 30th Ave, Long Island City, NY 11103, USA         6
```

**Comment by rmglazner** [comment]
Great, thank you! I added the drop-off image to the project report.

**Comment by JestonBlu** [comment]
Rachel, is there a place where you want me to save some of these plots? Ill probably tweak them over the next couple of days to make them look better.

**Comment by rmglazner** [comment]
It has honestly been the easiest when you upload the images in this discussion thread (as long as no one else minds!)

**Comment by JestonBlu** [comment]
Okay, i went ahead and created a folder in Taxi/Plots to store the files there just in case.. this might be a better one showing the 2 side by side... i have also removed the tick marks, text, and centered the titles.

![image](https://cloud.githubusercontent.com/assets/3339909/25202453/102fb6ae-251b-11e7-97df-8bdd47965fbe.png)

**Comment by rmglazner** [comment]
Thank you!

**Comment by JestonBlu** [comment]
I have added some data and an initial SAS script to the Taxi folder. I started to try some simple models, but I figured I would get all of this posted so you all can try your own models with the filtered data. 

I thought maybe a beta regression would be good if we were looking at the response being the proportion of tip to fare, but SAS is timing out on my PC when I try to run a bunch of the variables.  Anne and Shannon, do you two want to try creating some models with the prepped data set? Im going to continue to do so as well, but I think i will also concentrate on making some more plots for the report and presentation.

I think it would be neat if we find some significant locations or combinations of locations to also try to display that visually on a map as well.

**Comment by JestonBlu** [comment]
Forgot to mention, the data set in the taxi folder is a CSV. It has about 60K records and I have also attached the cluster locations so if you want to use it, the variables are pickup_location_id and dropoff_location_id... we can cross reference back to the address locations for the report and presentation, but I would just use the codes for now.

**Comment by profgeraci** [comment]
Joseph:
   I would love to look at the data and the SAS code you've written, but I can't read either of these two files.  Am I missing something?   Here's the SAS file:
![2017-04-19_1907](https://cloud.githubusercontent.com/assets/8108754/25205955/4a0c649a-2533-11e7-8bce-bdd292b65bf0.png)
And here's the CSV file:
![2017-04-19_1907_001](https://cloud.githubusercontent.com/assets/8108754/25205972/53d1ab3e-2533-11e7-9dea-b8995115937c.png)

**Comment by JestonBlu** [comment]
It might be better just to view the script through github. I think we are just using different encodings of the files... its still a csv file even if the windows preview is funny..  Ive copied the sas script below... see if you can run that.  You will have to make DTA equal to the csv file location on your computer.

```SAS
%LET DTA = 'cab_final.csv';

proc import datafile=&dta out=cab;
run;


/* Mixed Model with Random Var Dropoff Locations and Times */
ods graphics on;
proc glimmix data=cab plots=studentpanel;
	class month pickup_time dropoff_time toll_ind pickup_location_id dropoff_location_id;
	model tip_amount = trip_distance 
                       passenger_count 
                       month 
                       toll_ind 
                       / ddfm=kr;
	random pickup_location_id dropoff_location_id pickup_time dropoff_time;
	lsmeans month / adjust=tukey;
run;
ods graphics off;
```

**Comment by profgeraci** [comment]
OK, I can read the data files now.  I'm not sure what the problem was, but I think one of my computers was corrupting the file.  

I think it would be a good idea to have a brief meeting soon (maybe tonight?) so that we can discuss the plan for this project and agree on a model that we want to use.  

I'm available tonight or tomorrow night or all weekend.  When are you all available?

**Comment by JestonBlu** [comment]
I can make anytime work. Whatever is best for everyone else.

**Comment by rmglazner** [comment]
Can we meet at 7 tonight?

**Comment by profgeraci** [comment]
Yes, Rachael.  7pm tonight CT works - that's 8pm ET, right?  Is that ok with everyone?

**Comment by nitroys** [comment]
I can do 7CST, but not 7EST.

**Comment by JestonBlu** [comment]
Works for me.

**Comment by JestonBlu** [comment]
Ill be a few minutes late though.

**Comment by nitroys** [comment]
Thanks for posting everything, Joseph. I took down the data and the code and played around with a few additional models. I've added my code and pdf output to the taxi folder. 

I think the models predicting tip amount are the most interesting, personally. We can discuss more tonight, but I wanted to get these up for you guys to look at before then.

**Comment by rmglazner** [comment]
I keep forgetting that we are in different time zones, sorry! Yes, 7:00 central time works for me.

Google Hangouts work again?

**Comment by profgeraci** [comment]
Yes, that's great, Rachael.

See everyone at 7pm CST (8pm EST) on Google Hangouts

**Comment by JestonBlu** [comment]
Ive uploaded a new version of the Taxi data that includes the variable Rate code... I noticed when doing some distribution plots that there appears to be some significant differences between the rate code and tip amount. 

![image](https://cloud.githubusercontent.com/assets/3339909/25256760/d7c377e0-25f8-11e7-8b22-424c8094f9e2.png)

**Comment by profgeraci** [comment]
Here's the correlation and covariance table if you want to use it in the document or the presentation.
![2017-04-20_2047](https://cloud.githubusercontent.com/assets/8108754/25258059/a1b50152-260a-11e7-97bd-eaf6c6cb52a0.png)

**Comment by nitroys** [comment]
Hi all,

I've added more models and my output for the best models to the analysis folder. Even though we found fare amount to be more highly correlated with tip amount, it looks like distance gives us a more interesting model. I think this might be because distance is less correlated with the other predictors, whereas fare amount would be related to whether there were tolls, the rate code, etc. There are some interesting interactions going on too. 

The second model in that pdf removes the pickup and dropoff time effects, because the standard error for the pickup effect was larger than the variance estimate, so I was concerned about that.  

Let me know what you all think, and if you want to see the other models I tried, my SAS code is there as well. The PDF with the output from all of those was too big to upload :)

**Comment by JestonBlu** [comment]
Thanks Shannon. Can you double check that you uploaded the new PDF? I see the edited SAS code, but the the current PDF in the Taxi folder looks like its the same one from yesterday.

**Comment by nitroys** [comment]
Did you check the analysis folder? I put it there instead.

**Comment by JestonBlu** [comment]
Thanks, i think this looks good. Just a couple of questions. Do you think it would be better to make passenger count ordinal, that way each of the coefficients compare to adding one more passenger rather than comparing each to 6 passengers? It would also make sense to me then to make 1 passenger the base level.

Could you also generate the predictions with peason residuals and measure the variance of those residuals so we can get an estimate of goodness of fit on the full and reduced model?

Also would you be able to generate the individual estimates and significane of the random locations in a saved sas dataset? I would like to try to show the significant locations on the map somehow.

**Comment by rmglazner** [comment]
I think changing passengers to ordinal is a good idea.

**Comment by profgeraci** [comment]
That's a great idea to show the significant (high-tipping, right?) locations visually.  Very eye-catching. 

(Who says that statistics can't be sexy?)

**Comment by nitroys** [comment]
Okay! Thanks for the comments. I agree about passenger count - I had switched it to see each level in the solutions, but I agree the interpretation is better when it's ordinal. Our Pearson residuals look good in both models, just slightly better in the second. You can see them in the updated best_models.pdf. I've also added two SAS files with the solutions to the random effects for both models.

**Comment by JestonBlu** [comment]
Thanks Shannon, something I noticed about the Full and restricted models.. The full model has a better AIC than the restricted one which is an indication that our smaller model is no better. 

Also Im thinking that because we have so much data we should probably try a lot more of the interactions. I seem to remember Dr. Akleman saying that if you have enough data, you should try all of the interactions you can.

I was messing with your code a bit this morning and I saw that the log transformation is kicking out some records where there was no tip. I made an adjustment and added 1 to tip before the transformation and that seemed to make the model diagnostic plots look a lot better. It also made the residual variance a good bit smaller.. but it also looks like it made dropoff time worth keeping.

The code i played with is below. Im having trouble running the complex interactions on my machine. Would you be able to play with this and see what you get?  Also I was wondering if we could use an interaction term between pickup and dropoff locations... I think that would be interesting, but it may be taking too much computing time. My computer chokes when I try to run it, but Im running SAS off of a remote server from work so it may just be me.  

Let me know what you think.

```sas
%LET DTA = 'cab_final.csv';

proc import datafile=&dta out=cab replace;
run;

*proc contents data = cab; run;

data cab;
    set cab;
    log_tip = log(tip_amount + 1);
    log_dist = log(trip_distance);
    log_fare = log(fare_amount);
run;

/* Mixed Model with Random Var Dropoff Locations and Times */
ods graphics on;

title 'Log Model-response and distance logged, month and toll interactions-- Best Model';
proc glimmix data=cab plots=studentpanel;
	class month pickup_time dropoff_time 
		  toll_ind pickup_location_id dropoff_location_id 
 		  rate_code passenger_count;
	model log_tip = log_dist 
                       passenger_count 
                       month 
                       toll_ind
                       rate_code
		       passenger_count*month
		       passenger_count*toll_ind
		       passenger_count*rate_code
		       passenger_count*log_dist
		       month*toll_ind
		       month*rate_code
                       month*log_dist
		       toll_ind*rate_code
                       toll_ind*log_dist
		       rate_code*log_dist
		       passenger_count*month*toll_ind
		       passenger_count*month*rate_code
		       passenger_count*toll_ind*rate_code
		       month*toll_ind*rate_code
                       / ddfm=kr;
	random pickup_location_id 
			dropoff_location_id 
			pickup_time 
			dropoff_time;    
run;

title 'Best Model with time random effects removed';
proc glimmix data=cab plots=studentpanel;
	class month toll_ind pickup_location_id dropoff_location_id rate_code passenger_count ;
	model log_tip = log_dist 
                       passenger_count 
                       month 
                       toll_ind
                       rate_code
                       month*log_dist
                       toll_ind*log_dist
   		       month*toll_ind*passenger_count
                       / ddfm=kr solution;
	random pickup_location_id dropoff_location_id pickup_location_id*dropoff_location_id dropoff_time;
	output out=PRED pred=p resid=r pearson=presid;
	lsmeans passenger_count / oddsratio adjust=tukey cl;
	lsmeans month / oddsratio adjust=tukey cl;
	lsmeans toll_ind / oddratio adjust=tukey cl;
	lsmeans rate_code / oddsratio adjust=tukey cl;
run;

PROC UNIVARIATE data=pred;
var presid;
run;

ods graphics off;
```

**Comment by nitroys** [comment]
Hmm I'm having trouble too. I can try on Monday when I get back to my work computer, as I'm remoting in to our server right now too.

**Comment by JestonBlu** [comment]
It might just be that there are too many interactions with the 50x50 in the random statement. We might not be able to test that. What if you rip that part out for now?

**Comment by nitroys** [comment]
Okay, yeah, taking that part out made it work immediately. I called the output interaction_models.pdf, its in the analysis folder. There's a few additional significant interactions here. I don't have time today to really go in and play around with more, but I might tomorrow night.

**Comment by JestonBlu** [comment]
Sounds good, can you post the code you used to save the random variable estimates as a separate dataset?

**Comment by nitroys** [comment]
`ods listing close;
ods output  SolutionR = out.RandomEffectsReduced;
title 'Best Model with time random effects removed';
proc glimmix data=cab plots=studentpanel;
	class month toll_ind pickup_location_id dropoff_location_id rate_code;
	model log_tip = log_dist 
                       passenger_count 
                       month 
                       toll_ind
                       rate_code
                       month*log_dist
                       toll_ind*log_dist
                       / ddfm=kr solution;
	random pickup_location_id dropoff_location_id /solution;
*lsmeans month*LOG_DIST / slice=month slicediff = month adjust=tukey;
         output out=gmxout pred=pred
                     pred(ilink)=predmu
                     pearson=pearson;
*lsmeans month*LOG_DIST / slice=month slicediff = month adjust=tukey;     
run;

ods listing;`


Its the ods listing command. You can find the name of every table you can export from a procedure by running ods trace on before the procedure, and then ods trace off after it. It prints the names of the tables to your log. That's how I found the one i wanted was called SolutionR.

**Comment by JestonBlu** [comment]
Okay, here is what I have come with so far for displaying the random effects estimates on the map. I have 2 versions, one that shows the whole area, and one that zooms in on Manhattan because thats where the bulk of the data is.

My interpretation of the random estimates are in percent because the response variable is logged. Right now Im using Shannon's model that she used to generate the random effects estimates. If we make a refinement to the model, all I need is that same table reproduced and I will run it through the code i have written to generate the maps.  

My understanding with the random effects is that there is no base level so the percent change that I am I showing would be whatever the predicted tip is times the random effect estimate. So a value of .2 is a 20% tip increase vs an insignificant location.  Does that make sense?

![image](https://cloud.githubusercontent.com/assets/3339909/25314551/1cd60d7e-280c-11e7-84d0-723fde1f78cc.png)

![image](https://cloud.githubusercontent.com/assets/3339909/25314750/55d58412-280f-11e7-850b-2f04e31058bf.png)

A couple interesting takeaways... 
* There are more significant dropoff locations than pickup locations.
* High pickup effect locations are relatively close to the United Nations HQ and JFK Intl Airport
* Low pickup effect locations is relatively close to the Empire State Building
* High dropoff effect locations are near NYSE, N Bronx, Williamsburg Bridge Area, Hudson River Park, East Harlem, JFK Intl Airport
* Low dropoff effect locations are near NY University, Hudson Yards Railway Station

I can refine these more if we do anymore model tweaking

**Comment by nitroys** [comment]
I've uploaded another version of the interaction models pdf. I'm not really sure which one is best here though...hoping you all can give some feedback. 

The first model includes every possible interaction of fixed factors. The five-way interaction is significant, so I didn't remove any of the lower level interactions. But, a lot of the estimates are missing, and I'm not sure why there's not enough degrees of freedom for those levels...any ideas?

The second model I got by including only up to three way interactions and then removing insignificant interactions. The last model is the one Joseph had coded above. The AIC is smallest on the first model, but I don't like all the missing values. 

My code is there too, it's cab3.sas.

**Comment by rmglazner** [comment]
I really like the random effects maps! I will add them to the report later today. Should I move forward with recording a draft of the presentation today as originally planned? I am not sure which model is considered our final model at this point, so I do not know which information to focus on for that.

**Comment by profgeraci** [comment]
Hi all.  It looks like we are nearing consensus on the models.  I have some time today to work on the report (thanks for getting it started, Racheal).  I see that there are 3 PROC GLIMMIX reports in the latest PDF file - later today I will print them all out.  

Are we still going to present a FULL model, then a REDUCED model?  Or are we going to do more than that?   

It seems like Rachael can't really record a presentation until we decide which models we're going to present.

**Comment by JestonBlu** [comment]
Im tweaking the models Shannon posted right now so i wouldn't bother adding them to the report yet.  Ill post my feedback soon, around 1pm CST. I think we should present what we tried for the full model, but not go into any details, and just focus on the reduced model.

**Comment by JestonBlu** [comment]
Okay, I have made some edits to the models... the main thing I changed was passenger_count to a class variable and I removed distance from all of the interactions so that only the class variables have interactions. This appears to make the the model diagnostic plots look much better.

![image](https://cloud.githubusercontent.com/assets/3339909/25350000/3e6c2634-28e9-11e7-8029-5cdb19291724.png)

I have uploaded two files with pdf output (Final_Full_Model, Final_Reduced_Model). The full model is the same model Shannon listed only with the changes I made above. The 4way interaction was insignificant so I removed it, then I removed each of the 3way interactions except for one that was significant, then I stopped. 

Now a lot more of the LSMeans tables are populated. I think the issue before was the N-way interactions were causing the main effects and 2way interactions to be confounded and unestimatable. 

Since there are so many large estimate tables, I think we should focus the presentation on the smaller main effects tables or simple two way interactions like toll_ind and rate code for example.

The only issue I have is that the full model has a lower AIC then the Reduced Model and I think that may come up... I wonder if that is a byproduct of having a lot of data and relatively few predictors.

What does everyone think about these models?  The code is cab4.sas

**Comment by rmglazner** [comment]
I will wait until this afternoon to create the presentation, so I will have something uploaded later tonight. This will give everyone time tomorrow to watch it before we meet again. What time works for everyone to meet tomorrow afternoon or evening?

**Comment by JestonBlu** [comment]
Same time as last week, 7cst works for me

**Comment by rmglazner** [comment]
The models look good! The reduced model still contains some insignificant interactions, is that okay? Specifically, toll*passenger and month*rate. Passenger is significant individually, but toll, month, and rate are not. I am assuming those predictors were kept in the reduced model because of their other significant interactions.

**Comment by rmglazner** [comment]
7 central time works for me too!

**Comment by profgeraci** [comment]
Yes, 7pm CT is good (8pm ET).

**Comment by JestonBlu** [comment]
Ive updated the significant effects map with the latest model. Ive also added a chart of significant effects for dropoff hour which seemed to be significant.

Most of the original statements about the significant locations were true even after the model revision, but a few have changed so here it is:

*  There are more significant dropoff locations than pickup locations.
*  High pickup effect locations are relatively close to the United Nations HQ and Nomad District
*  Low pickup effect locations are areas around the Empire State Building and Hunters Point on Long Island
*  High dropoff effect locations are near NYSE, N Bronx, Williamsburg Bridge Area, Hudson River Park, East Harlem, JFK Intl Airport
*Low dropoff effect locations are near NY University, Hudson Yards Railway Station

![image](https://cloud.githubusercontent.com/assets/3339909/25354749/d606606c-28f9-11e7-891e-3c8d4418d58a.png)

![image](https://cloud.githubusercontent.com/assets/3339909/25354888/5825597c-28fa-11e7-82ba-1f9c35138e30.png)

![image](https://cloud.githubusercontent.com/assets/3339909/25354925/77ceffd0-28fa-11e7-9aeb-5701c995e5aa.png)

**Comment by JestonBlu** [comment]
@rmglazner yeah, since the higher order interactions were significant, I believe you aren't supposed to remove the lower ones even if they show as being insignificant. Im not 100% sure if thats a hard rule. The main reason I didnt remove any more is because of the AIC/BIC scores. Since the full model has the lowest score I think its technically the best model, so in this case I think its better to leave in as many variables  as possible once the the highest order interactions are significant.

**Comment by rmglazner** [comment]
That makes sense, thank you for explaining!

**Comment by nitroys** [comment]
I feel like the type III estimates table for the full model is still weird...I don't like the infinite F values and the p-values of 1. I'm not sure why it's happening, but I'm guessing it has something to do with the number or interactions in the model and whatever the kenward roger calculation does. So I lean toward the reduced model, despite the higher AIC. The corrected AICs are the same as the regular AICs here, which is strange to me, so I'm not sure how much i trust them. 

I second what Joseph says about keeping in lower level interactions when the high level interaction is significant. It's similar to keeping insignificant main effects when the interaction is significant, just a few levels up. 

So overall, I think the reduced model is better for our purposes. The residuals look similar in each, and I don't have a lot of stock in the AIC values, especially when they're roughly only 1% lower in one model. Also, 7pm CST tomorrow works for me.

**Comment by JestonBlu** [comment]
I think AIC and AICc converges as observations increase. I agree with everything Shannon has said.

**Comment by rmglazner** [comment]
Based on this information, I will move forward with the reduced model. I have a meeting for another group project at 5:00 today, so I will start working on our presentation after that. I should have a video up tonight, which gives everyone time before tomorrow evening's meeting to view it and think of any changes to be made!
