### ISSUE TITLE
Background on NWRoc

### ISSUE THREAD

**Issue by profgeraci** [JestonBlu/Neighbor-Works#3]
Hi guys.  I can't remember if I told you the genesis of this NWRoc data, so I'll do so here.  I was contacted by this agency (NeighborWorks) to participate in what we call a Service Learning (SL) project.  The basic idea is that St. John Fisher College (SJFC) pairs itself with various community agencies for mutual gain.   The students gain knowledge and real-world experience as they solve problems and provide services to the community.  The community gains the expertise and manpower to solve some of their problems. 

We completed a project plan for the SL project, which I will provide here for background: 

[Geraci- Neighborworks- CP updated 12.9 fac updated 1.11.docx](https://github.com/JestonBlu/Neighbor-Works/files/763673/Geraci-.Neighborworks-.CP.updated.12.9.fac.updated.1.11.docx)

The problem that has been posed by NWRoc is this:  

NWRoc is in Year 3 of a five-year project aimed at rejuvenating what they call the "Triangle" area of Rochester.  There's a map of this area here:

[NW Roc Geographical Boundary Map.pdf](https://github.com/JestonBlu/Neighbor-Works/files/763674/NW.Roc.Geographical.Boundary.Map.pdf)

   During 2016 they conducted a mid-term survey of the neighborhood to judge their success relative to the benchmark survey that was conducted at the beginning of the project (we'll assume that was in 2013).  

The agency would like to know if there is a statistical and significant difference between the four geographical sub-neighborhoods (designated 1 through 4 on the map) for the following aspects of community life: 

a)	Satisfaction Level
b)	Participation in the Community
c)	Willingness to Become Involved
d)	Opinion on Police Response
e)	Safety
f)	Community Improvement Perceptions
g)	Homeownership
h)	Age, racial, and gender composition

So, I have committed to NWRoc to do the following two things:

(1) My MATH130 students (see attached document) will be completing an assignment: 

[Memo Problem 2.docx](https://github.com/JestonBlu/Neighbor-Works/files/763664/Memo.Problem.2.docx)

.... but since I only teach descriptive statistics and linear regression in this course, my students will not be able to judge statistical significance between the sub-neighborhoods.    I've compose a "sample solution" of the type of thing I think my students will do: 

[Memo#2NWRocTNW SOLUTION.docx](https://github.com/JestonBlu/Neighbor-Works/files/763670/Memo.2NWRocTNW.SOLUTION.docx)

(2)  The second part to this project is what this STAT653 group (that's the four of us) will do.  Since we have been learning about the various analysis methods, I'm hoping that we can provide the "statistically significant" part of the NWRoc request.

**Comment by JestonBlu** [comment]
Thanks for the background. This was very helpful for me. One thing that immediately comes to mind are tests of independence and association to see if the responses between the neighborhoods are actually different, which seems to be a primary interest in your study. I did some of this in a previous categorical data analysis course. Ill try to dig up some examples.
