### ISSUE TITLE
More Background on Neighbor Works

### ISSUE THREAD

**Issue by profgeraci** [JestonBlu/Neighbor-Works#4]
OK, so the Neighbor Works agency came to campus this week to do an orientation for my MATH130 students.  Here's a picture of them - names are Eric Van Dusen (left) and Monica Finger (on right). 

![sitevisit7feb2017](https://cloud.githubusercontent.com/assets/8108754/22804402/f28356fc-eee6-11e6-930d-a8fd854db058.JPG)

Interesting points that I heard:
- Population of households in entire Triangle area is 1200.  They selected a random sample of 450, got a nearly 50% return-rate (200 households), sometimes after returning to the household multiple times. 
- Students asked if they go many rejections.  Answer:  Not that many as long as they came at a convenient time (typically 7pm - 9pm).  
- When asked what they would consider the most important response variable for their mission, they indicated two variables:
(1) Would you recommend this neighborhood to a friend? [RECOMMEND]
(2) How will the community change in the next three years?  [ChangeNext3Y]
_this last point surprised me - I thought they would be more concerned with the Current Satisfaction - they seem to be more concerned with the "hope for the future"._

Here's the PPT they used for the presentation - good graphics!

[HB Presentation.pptx](https://github.com/JestonBlu/Neighbor-Works/files/765089/HB.Presentation.pptx)

**Comment by rmglazner** [comment]
Thanks for sharing this!
