### ISSUE TITLE
Project Document

### ISSUE THREAD

**Issue by profgeraci** [JestonBlu/Neighbor-Works#6]
Does anyone have a template that we can use for the project?  It seems like something like this one (from the archives) might be appropriate.  Does anyone have a MS Word document already setup with preferred margins, headings, etc?

I'll start working on the background/ project objective write up tomorrow.  I just spent all day yesterday and this morning getting through Video 10 - I need a break.   8-) 
- Anne

[amoako_derrick1.pdf](https://github.com/JestonBlu/Neighbor-Works/files/785997/amoako_derrick1.pdf)

**Comment by rmglazner** [comment]
I remember that Dr. Akleman posted links to previous projects earlier this semester. I have copied and pasted them here, which hopefully helps!

http://lectures.stat.tamu.edu/Lectures/stat653_spr2015_projects/projects2015.html

http://lectures.stat.tamu.edu/Lectures/stat653_spr2016_projects/projects2016updated.html

**Comment by rmglazner** [comment]
I think Times New Roman double-spaced would probably work best, but I am happy with what everyone else wants if it is something different!

**Comment by JestonBlu** [comment]
Ill defer to you all on this one.

**Comment by rmglazner** [comment]
Would it be possible to have the introduction and model first drafts uploaded by next Monday so I have time to put together a presentation draft for us to discuss (and practice the talk)?

**Comment by JestonBlu** [comment]
Ill plan on having a first model ready by Saturday.

**Comment by rmglazner** [comment]
Great, thank you!
